baseURL = 'https://yes-but-no.github.io/'
languageCode = 'en-us'
title = 'Yes, But Actually No'
theme = 'anubis2'

[pagination]
pagerSize = 5

[params.author]
name = "YBN"
email  = "admin@yes-but-no.org"
location = "Singapore"

[params]
description = "Yes But No But Yes But No But Yes But No But Yes But No But Yes"
dateFormat = "2006-01-02"
paginationSinglePost = true

colorTheme = "dark"
colorThemeSwitcher = true

readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = false # true: enable mathjax globally (default is false)
toc = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'base16-snazzy'
tabWidth           = 4